# Model Configuration for House Price Prediction
# Hyperparameters, model settings, and training configuration

model_settings:
  # Random seed for reproducibility
  random_state: 42
  
  # Model types to train and compare
  models:
    linear:
      name: "LinearRegression"
      params: {}
    
    ridge:
      name: "Ridge"
      params:
        alpha: 1.0
        random_state: 42
    
    lasso:
      name: "Lasso"
      params:
        alpha: 0.1
        random_state: 42
        max_iter: 2000
    
    elasticnet:
      name: "ElasticNet"
      params:
        alpha: 0.1
        l1_ratio: 0.5
        random_state: 42
        max_iter: 2000

hyperparameter_tuning:
  # Cross-validation settings
  cv_folds: 3
  scoring: "neg_root_mean_squared_error"
  
  # Parameter ranges for tuning
  ridge_alphas: [0.001, 0.01, 0.1, 1.0, 10.0, 100.0]
  lasso_alphas: [0.0001, 0.001, 0.01, 0.1, 1.0, 10.0]
  elasticnet_alphas: [0.0001, 0.001, 0.01, 0.1, 1.0, 10.0]
  elasticnet_l1_ratios: [0.1, 0.3, 0.5, 0.7, 0.9]

feature_selection:
  # Number of top features to select
  k_features: 12
  scoring_method: "f_regression"
  
preprocessing:
  # Scaling method
  scaler: "RobustScaler"  # Options: StandardScaler, RobustScaler, MinMaxScaler
  
  # Outlier handling
  outlier_method: "iqr"  # Options: iqr, quantile
  iqr_multiplier: 1.5
  quantile_lower: 0.05
  quantile_upper: 0.95
  
  # Target encoding
  target_encoding:
    n_folds: 5
    smoothing: 20

evaluation:
  # Train/validation/test split ratios
  test_size: 0.2
  val_size: 0.2
  
  # Performance targets
  target_rmse_log: 0.5
  target_r2: 0.8
  target_training_time_minutes: 5
  target_memory_gb: 4